[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "tfd-decomp"
version = "0.1.0"
description = "Nonstationary signal decomposition using quadratic time-frequency distributions"
readme = "README.md"
requires-python = ">=3.11"
license = "BSD-3-Clause"
authors = [
  {name = "John M. O'Toole"},
  {name = "Nathan J. Stevenson"},
]
dependencies = [
  "numpy>=1.26",
  "scipy>=1.12",
  "matplotlib>=3.8",
]

[project.optional-dependencies]
dev = [
  "flake8>=7",
  "pytest>=8",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["tests"]

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203"]

